/**
 * Lovable managed OAuth broker — STUB.
 *
 * In a generated app this file is auto-generated by Lovable (backed by
 * `@lovable.dev/cloud-auth-js`) and provides the real broker. It is committed here
 * only so the base starter (and its forks) type-check and run without the generated
 * backend. Lovable overwrites it at remix — do not rely on this stub's behavior.
 *
 * OAuth MUST go through this broker, never `supabase.auth.signInWithOAuth` (that path
 * throws `missing OAuth secret`). See docs/design/auth-and-navigation.md.
 */

export interface OAuthOptions {
  /** MUST be `${window.location.origin}/auth/callback` — never bare origin. */
  redirect_uri: string;
}

export interface OAuthResult {
  /** True while the browser is navigating to the provider. */
  redirected?: boolean;
  /** Present when the provider isn't configured or the call failed. */
  error?: { message: string } | null;
}

export const lovable = {
  auth: {
    async signInWithOAuth(
      _provider: "google" | "apple",
      _options: OAuthOptions,
    ): Promise<OAuthResult> {
      // Stub: real broker is injected by Lovable at generation. Until then, report
      // "not configured" so the UI degrades gracefully instead of throwing.
      return { error: { message: "OAuth provider not configured (stub broker)" } };
    },
  },
};
